server:
  port: 9094
spring:
  redis:
    host: 192.168.98.98
    port: 6379
    password: redis
    jedis:
      pool:
        max-active: 10
  rabbitmq:
    host: 192.168.98.98
    port: 5672
    username: user
    password: user
    virtual-host: /user
  application:
    name: order-service
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/