spring:
  application:
    name: regist-service
  datasource:
    url: jdbc:mysql://192.168.98.98:3306/qf-v6?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  redis:
    port: 6379
    host: 192.168.98.98
    password: redis

server:
  port: 8762

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


