
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  redis:
    host: 192.168.71.71
    port: 6379
    password:
    jedis:
      pool:
        max-active: 20
server:
  port: 8764
spring:
  application:
    name: sms-service
